[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string]$DriverDirectory,
    [switch]$AcceptLocalTestCertificate
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$TargetDeviceId = 'VID_0471&PID_0111&MI_03'
$TargetInstancePrefix = "USB\$TargetDeviceId\"
$AudioInstancePrefix = 'USB\VID_0471&PID_0111&MI_00\'
$PnpUtil = Join-Path $env:WINDIR 'System32\pnputil.exe'

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-PnpServiceName {
    param([Parameter(Mandatory = $true)][string]$InstanceId)

    $property = Get-PnpDeviceProperty -InstanceId $InstanceId -ErrorAction SilentlyContinue |
        Where-Object { $_.KeyName -eq 'DEVPKEY_Device_Service' } |
        Select-Object -First 1

    if ($null -eq $property) {
        return $null
    }

    return [string]$property.Data
}

function Get-PhilipsDeviceNodes {
    Get-PnpDevice -ErrorAction SilentlyContinue |
        Where-Object { $_.InstanceId -like 'USB\VID_0471&PID_0111*' }
}

function Assert-DriverPackageTargetsMi03Only {
    param(
        [Parameter(Mandatory = $true)][string]$InfPath,
        [Parameter(Mandatory = $true)][string]$CatalogPath
    )

    if (-not (Test-Path -LiteralPath $InfPath)) {
        throw "INF not found: $InfPath"
    }
    if (-not (Test-Path -LiteralPath $CatalogPath)) {
        throw "Catalog not found: $CatalogPath"
    }

    $infText = Get-Content -LiteralPath $InfPath -Raw
    if ($infText -notmatch '(?im)^\s*DeviceID\s*=\s*"VID_0471&PID_0111&MI_03"\s*$') {
        throw 'Refusing to install: INF DeviceID is not exactly VID_0471&PID_0111&MI_03.'
    }
    if ($infText -notmatch '(?im)^\s*%DeviceName%\s*=\s*USB_Install\s*,\s*USB\\%DeviceID%\s*$') {
        throw 'Refusing to install: INF install line does not bind through USB\%DeviceID%.'
    }
    if ($infText -match 'VID_0471&PID_0111&MI_00') {
        throw 'Refusing to install: INF mentions MI_00, the audio interface.'
    }
}

function Trust-TestCertificateIfAllowed {
    param(
        [Parameter(Mandatory = $true)][string]$CertificatePath,
        [Parameter(Mandatory = $true)][string]$CatalogPath
    )

    $signature = Get-AuthenticodeSignature -LiteralPath $CatalogPath
    if ($signature.Status -eq 'Valid') {
        Write-Host "Catalog signature is already trusted: $($signature.SignerCertificate.Subject)"
        return
    }

    if (-not $AcceptLocalTestCertificate) {
        throw "Catalog signature is not trusted ($($signature.Status)). Re-run with -AcceptLocalTestCertificate for local/test libwdi packages, or ship a production-signed driver."
    }

    if (-not (Test-Path -LiteralPath $CertificatePath)) {
        throw "Certificate not found: $CertificatePath"
    }

    Write-Host 'Importing local test certificate into LocalMachine Root and TrustedPublisher...'
    Import-Certificate -FilePath $CertificatePath -CertStoreLocation Cert:\LocalMachine\Root | Out-Null
    Import-Certificate -FilePath $CertificatePath -CertStoreLocation Cert:\LocalMachine\TrustedPublisher | Out-Null

    $signature = Get-AuthenticodeSignature -LiteralPath $CatalogPath
    if ($signature.Status -ne 'Valid') {
        throw "Catalog is still not trusted after certificate import: $($signature.Status)"
    }
}

if (-not (Test-IsAdministrator)) {
    throw 'Run this script from an elevated PowerShell window.'
}

if ([string]::IsNullOrWhiteSpace($DriverDirectory)) {
    $AppRoot = Split-Path -Parent $PSScriptRoot
    $DriverDirectory = Join-Path $AppRoot 'driver\winusb-philips-mi03'
}

$DriverDirectory = (Resolve-Path -LiteralPath $DriverDirectory).Path
$InfPath = Join-Path $DriverDirectory 'philips_audio_set_(interface_3).inf'
$CatalogPath = Join-Path $DriverDirectory 'Philips_Audio_Set_(Interface_3).cat'
$CertificatePath = Join-Path $DriverDirectory 'philips_mi03_libusb_autogenerated.cer'

Assert-DriverPackageTargetsMi03Only -InfPath $InfPath -CatalogPath $CatalogPath
Trust-TestCertificateIfAllowed -CertificatePath $CertificatePath -CatalogPath $CatalogPath

$devices = @(Get-PhilipsDeviceNodes)
$audio = @($devices | Where-Object { $_.InstanceId -like $AudioInstancePrefix })
$control = @($devices | Where-Object { $_.InstanceId -like "$TargetInstancePrefix*" })

if ($audio.Count -eq 0) {
    Write-Warning 'The Philips audio interface MI_00 is not currently visible. Installation will continue, but playback must be verified after reconnect.'
} else {
    foreach ($node in $audio) {
        $service = Get-PnpServiceName -InstanceId $node.InstanceId
        if ($service -eq 'WinUSB') {
            throw "Refusing to continue: audio interface MI_00 is using WinUSB ($($node.InstanceId)). Restore MI_00 before installing."
        }
        Write-Host "Audio interface preserved: $($node.InstanceId) service=$service"
    }
}

if ($control.Count -eq 0) {
    Write-Warning 'The Philips control interface MI_03 is not currently visible. The driver package will be staged and applied when the device appears.'
} else {
    foreach ($node in $control) {
        Write-Host "Control interface target: $($node.InstanceId) service=$(Get-PnpServiceName -InstanceId $node.InstanceId)"
    }
}

if ($PSCmdlet.ShouldProcess($InfPath, 'Install WinUSB on Philips MI_03 only')) {
    & $PnpUtil /add-driver $InfPath /install
    if ($LASTEXITCODE -ne 0) {
        throw "pnputil /add-driver failed with exit code $LASTEXITCODE."
    }

    & $PnpUtil /scan-devices
    if ($LASTEXITCODE -ne 0) {
        throw "pnputil /scan-devices failed with exit code $LASTEXITCODE."
    }
}

$devices = @(Get-PhilipsDeviceNodes)
$audio = @($devices | Where-Object { $_.InstanceId -like $AudioInstancePrefix })
$control = @($devices | Where-Object { $_.InstanceId -like "$TargetInstancePrefix*" })

foreach ($node in $audio) {
    $service = Get-PnpServiceName -InstanceId $node.InstanceId
    if ($service -eq 'WinUSB') {
        throw "Post-check failed: MI_00 is using WinUSB ($($node.InstanceId))."
    }
    Write-Host "Post-check MI_00 OK: $($node.InstanceId) service=$service"
}

$winUsbCount = 0
foreach ($node in $control) {
    $service = Get-PnpServiceName -InstanceId $node.InstanceId
    Write-Host "Post-check MI_03: $($node.InstanceId) service=$service"
    if ($service -eq 'WinUSB') {
        $winUsbCount += 1
    }
}

if ($control.Count -gt 0 -and $winUsbCount -eq 0) {
    throw 'Post-check failed: MI_03 is present but not using WinUSB.'
}

Write-Host 'Driver installation completed without targeting MI_00.'
